name: kolaka
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.17+17

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  badges: ^3.1.1
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.14.0
  cloud_firestore_platform_interface: ^6.1.0
  cloud_firestore_web: ^3.6.1
  collection: ^1.17.2
  count_stepper: ^0.0.4
  easy_debounce: ^2.0.3
  equatable: ^2.0.5
  expandable: 5.0.1
  firebase_auth: ^4.6.3
  firebase_auth_platform_interface: ^7.0.9
  # firebase_auth_web: 5.2.0
  firebase_core: ^2.14.0
  firebase_core_platform_interface: ^5.0.0
  # firebase_core_web: 2.0.2
  floating_bottom_navigation_bar: 1.5.2
  flutter_animate: ^4.2.0
  flutter_cache_manager: ^3.3.1
  flutter_google_places: 
    git:
      url: https://github.com/fluttercommunity/flutter_google_places
      ref: v0.3.2
  flutter_plugin_android_lifecycle: ^2.0.15
  flutter_rating_bar: 4.0.1
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.4.0
  from_css_color: 2.0.0
  google_fonts: ^4.0.4
  google_maps: ^6.3.0
  google_maps_flutter: ^2.3.1
  google_maps_flutter_platform_interface: ^2.2.7
  google_maps_flutter_web: ^0.5.0+1
  google_sign_in: ^6.1.4
  google_sign_in_android: ^6.1.16
  google_sign_in_ios: ^5.6.2
  google_sign_in_platform_interface: ^2.4.1
  google_sign_in_web: ^0.12.0+2
  intl: 0.18.1
  json_path: 0.6.3
  location_picker_flutter_map: 1.2.0
  location: ^5.0.3
  mime_type: 1.0.0
  package_info_plus: ^4.0.2
  package_info_plus_platform_interface: 2.0.1
  page_transition: ^2.0.9
  path_provider: ^2.0.15
  path_provider_android: ^2.0.27
  path_provider_foundation: ^2.2.3
  path_provider_platform_interface: ^2.1.1
  photo_view: 0.14.0
  pin_code_fields: ^8.0.1
  plugin_platform_interface: ^2.1.4
  provider: ^6.1.1
  rxdart: 0.27.7
  sensors_plus: 1.4.1
  shake: 2.2.0
  shared_preferences: ^2.1.2
  shared_preferences_android: ^2.1.4
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: ^2.3.2
  # shared_preferences_web: ^2.2.2
  sign_in_with_apple: ^5.0.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  sliding_up_panel2: ^3.3.0+1
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.2.8+4
  stop_watch_timer: ^3.0.2
  stream_transform: 2.1.0
  styled_divider: ^1.0.5
  syncfusion_flutter_core: ^24.1.45
  syncfusion_flutter_datepicker: ^24.1.45
  table_calendar: 3.0.9
  time_picker_sheet: ^0.0.2+1
  timeago: ^3.4.0
  url_launcher: ^6.1.11
  url_launcher_android: ^6.0.35
  url_launcher_ios: ^6.2.3
  url_launcher_platform_interface: ^2.1.3
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.8.0
  webview_flutter_platform_interface: ^2.3.1
  webview_flutter_wkwebview: ^3.5.0
  webviewx_plus: 0.3.3
  carousel_slider: ^4.0.0
  flutter_screenutil: ^5.8.4
  flutter_spinkit: ^5.0.0
  flutter_polyline_points: ^1.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  firebase_storage: ^11.2.3
  syncfusion_flutter_calendar: ^24.1.45
  barcode_widget: ^2.0.4
  get: ^4.6.5
  flutter_barcode_scanner: ^2.0.0
  share_plus: ^7.1.0
  numberpicker: ^2.1.2
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.9
  infinite_scroll_pagination: ^4.0.0
  onesignal_flutter: ^5.0.3
  get_storage: ^2.1.1
  geocoding: ^2.1.1
  dio: ^5.4.0
  connectivity: ^3.0.6
  map_location_picker: ^1.2.1
  place_picker: ^0.10.0
  open_street_map_search_and_pick: ^0.1.0
  flutter_osm_plugin: any
  fluttertoast: any
  flutter_svg: ^2.0.9
  auto_size_text: ^3.0.0
  http: ^0.13.3
  image_picker: ^1.0.7
  uni_links: ^0.5.1
  file_picker: ^6.1.1
  video_player: ^2.7.2
  video_player_android: ^2.4.8
  video_player_avfoundation: ^2.4.6
  video_player_platform_interface: ^6.2.2
  video_player_web: ^2.0.16
  # flutter_statusbarcolor: ^0.9.10
  shimmer: ^3.0.0
 


dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/app_launcher_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/va/
    - assets/images/marker/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/category-icon/
    - assets/images/loading_kolaka.png


  fonts:
    - family: IconSax
      fonts:
        - asset: assets/fonts/IconSax.ttf
    - family: MyIcon
      fonts:
        - asset: assets/fonts/MyIcon.ttf
    - family: MyIcon2
      fonts:
        - asset: assets/fonts/MyIcon2.ttf
    - family: MyIcon3
      fonts:
        - asset: assets/fonts/MyIcon3.ttf
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
